version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: marat
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: WarehouseManagement_development
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_USERNAME: marat
      DATABASE_PASSWORD: 1234
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db

volumes:
  db_data: